### ISSUE TITLE
Error on step "compileJava", :compileJava FAILED

### ISSUE THREAD

**Issue by Evigilans** [Microsoft/malmo#561]
Hi there! I tried to run launchClient, but on step "compileJava" i got 100 errors and I do not know where the probem is. I use Windows 10 and JDK 8 131.

Thank you in advance!

Link the console output (did't link all the errors):

C:\Users\Egor\Malmo-0.22.0-Windows-64bit\Minecraft>launchClient.bat
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-eb2e450
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources
:applySourcePatches
:remapMcSources SKIPPED
:recompileMc SKIPPED
:extractNatives SKIPPED
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 194/1196   16%
Current status: 492/1196   41%
Current status: 780/1196   65%
Current status: 1053/1196   88%
:makeStart
:setupDecompWorkspace

BUILD SUCCESSFUL

Total time: 49.322 secs
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-eb2e450
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient UP-TO-DATE
:copyModToServer UP-TO-DATE
:deleteSchemas
:copySchemas
:jaxb UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
C:\Users\Egor\Malmo-0.22.0-Windows-64bit\Minecraft\build\sources\main\java\com\microsoft\Malmo\Client\ClientStateMachine.java:51: error: cannot find symbol
import net.minecraft.util.ChatComponentText;
                         ^
  symbol:   class ChatComponentText
  location: package net.minecraft.util

/////////////
98 ERRORS
/////////////

C:\Users\Egor\Malmo-0.22.0-Windows-64bit\Minecraft\build\sources\main\java\com\microsoft\Malmo\Client\ClientStateMachine.java:681: error: configID has private access in ConfigChangedEvent
            if (ev.configID.equals(MalmoMod.SOCKET_CONFIGS))
                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
100 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.606 secs
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-eb2e450
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient UP-TO-DATE
:copyModToServer UP-TO-DATE
:deleteSchemas
:copySchemas
:jaxb UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
C:\Users\Egor\Malmo-0.22.0-Windows-64bit\Minecraft\build\sources\main\java\com\microsoft\Malmo\Client\ClientStateMachine.java:51: error: cannot find symbol
import net.minecraft.util.ChatComponentText;
                         ^
  symbol:   class ChatComponentText
  location: package net.minecraft.util

/////////////////////
98 ERROR... AGAIN
/////////////////////

C:\Users\Egor\Malmo-0.22.0-Windows-64bit\Minecraft\build\sources\main\java\com\microsoft\Malmo\Client\ClientStateMachine.java:681: error: configID has private access in ConfigChangedEvent
            if (ev.configID.equals(MalmoMod.SOCKET_CONFIGS))
                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
100 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.487 secs

C:\Users\Egor\Malmo-0.22.0-Windows-64bit\Minecraft>

**Comment by katja-hofmann** [comment]
Hi @Evigilans,

thank you for reporting this. It looks like you're working with 0.22 where we had issues with caching. Could you try 0.30 instead?

**Comment by DaveyBiggers** [comment]
To follow on from what @katja-hofmann says, it looks like you have some peculiar version mismatch. In particular, it looks like you've at least partially upgraded to version 0.30.0 (as evidenced by the message `"This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril."`) - but the java code you are trying to compile seems like the _old_ (MC 1.8) Mod code. 
For example, this error:
```
C:\Users\Egor\Malmo-0.22.0-Windows-64bit\Minecraft\build\sources\main\java\com\microsoft\Malmo\Client\ClientStateMachine.java:681: error: configID has private access in ConfigChangedEvent
if (ev.configID.equals(MalmoMod.SOCKET_CONFIGS))
```
is caused by the fact that `ev.configID` changed from public to private access in between the MC1.8 and MC1.11 Forge code. The corresponding line in ClientStateMachine.java should also have changed (to use `getConfigID()`), but apparently you are compiling an old copy of that file.

Have you somehow only partially updated your source tree? Or maybe you have cache issues and need to clean and rebuild?

**Comment by DaveyBiggers** [comment]
Am closing this due to inactivity, but if this is still a problem, please reopen and provide some more details.
