### ISSUE TITLE
Compilation errors on Ubuntu 14.04 - 32 bit

### ISSUE THREAD

**Issue by okkhoy** [Microsoft/malmo#466]
When I try to build on a 32 bit Ubuntu 14.04, I get the following error:

```
$ make install
[  1%] Generating C++ from XSD files...
/usr/bin/xsd: 2: /usr/bin/xsd: Syntax error: ")" unexpected
make[2]: *** [Malmo/src/Mission.h] Error 2
make[1]: *** [Malmo/src/CMakeFiles/Malmo.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by okkhoy** [comment]
This was following the [build_linux](https://github.com/Microsoft/malmo/blob/master/doc/build_linux.md) document.

I realize the issue is here in the instruction:

6. On Debian 7 and Ubuntu 14.04 only: Install CodeSynthesis XSD:
`wget http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb`

Need to update the instruction to reflect 32 bit
`wget http://codesynthesis.com/download/xsd/4.0/linux-gnu/i686/xsd_4.0.0-1_i386.deb`
