### PR TITLE
Fix build linux md

### LINKED ISSUE #466: Compilation errors on Ubuntu 14.04 - 32 bit
When I try to build on a 32 bit Ubuntu 14.04, I get the following error:

```
$ make install
[  1%] Generating C++ from XSD files...
/usr/bin/xsd: 2: /usr/bin/xsd: Syntax error: ")" unexpected
make[2]: *** [Malmo/src/Mission.h] Error 2
make[1]: *** [Malmo/src/CMakeFiles/Malmo.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by okkhoy**
Fixes #466

### CODE REVIEW

**Comment by katja-hofmann** [comment]
Hi @okkhoy, thanks for debugging this and contributing the fix!
